spring: 
  profiles: 
    active: 
      - dev

---
spring: 
  profiles: dev
  application:
    name: microservicecloud-config-vip-dev
server: 
  port: 7080
---
spring: 
  profiles: test
  application: 
    name: microservicecloud-config-vip-test